FROM python:3.12.4-slim
LABEL maintainer="SorinoSSK"

ARG APP_UID=1000
ARG APP_GID=1000

RUN groupadd -g ${APP_GID} bot_orchestrator_grp && \
    useradd -u ${APP_UID} -g bot_orchestrator_grp -m bot_orchestrator_usr

WORKDIR /bot_orchestrator

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY bot_orchestrator_application ./bot_orchestrator_application
RUN mkdir -p ./bot_orchestrator_application/data/logs && \
    chown -R bot_orchestrator_usr:bot_orchestrator_grp ./bot_orchestrator_application/data

USER bot_orchestrator_usr
ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "bot_orchestrator_application.main"]
