FROM python:3.12.4-slim
LABEL maintainer="SorinoSSK"

ARG APP_UID=1000
ARG APP_GID=1000

RUN groupadd -g ${APP_GID} telegram_gateway_grp && \
    useradd -u ${APP_UID} -g telegram_gateway_grp -m telegram_gateway_usr

WORKDIR /telegram_gateway

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN mkdir -p ./telegram_gateway_application/data/logs && \
    chown -R telegram_gateway_usr:telegram_gateway_grp ./telegram_gateway_application/data

USER telegram_gateway_usr

CMD ["python", "-m", "telegram_gateway_application.main"]
